### ISSUE TITLE
Environment Lifecycle "Rebuilds" section is unclear

### ISSUE THREAD

**Issue by balorette** [cdr/docs#46]
Issue:
Documentation on the environment lifecycle is missing a word or two. 

Specific Section: 
https://coder.com/docs/environments/lifecycle#rebuilds

Paragraph:
Only the /home directory is persisted between rebuilds. This allows the Image to populated system development dependencies without interfering with any source code or miscellaneous configuration unique to your individual development environment.

Summary:
That second sentence doesn't make sense as is.

**Comment by vapurrmaid** [comment]
Thanks for reporting @balorette
